### ISSUE TITLE
Not able to anotate images.

### ISSUE THREAD

**Issue by shubhampateliitm** [mubastan/scene-text-annotation-tool-py#2]
The brush works fine but I am not able to annotate any image using the tool. The tool is not working properly. Can you provide any extra information about the configuration that I should use that might make the working of the tool feasible?

My System Config.
Ubuntu 16.04 16 gb ram, Anaconda python 2.7 and pyqt4.8
Thanks.

**Comment by shubhampateliitm** [comment]
I am also not able to see jpeg files.
Means it is loading on the left sidebar but not visible in image space.

**Comment by mubastan** [comment]
I have just downloaded and tried the tool on a jpg image, it worked properly (Linux Mint 18.2, kernel 4.15, Python 2.7). You may be missing some basic libs. Check the command line and see if there are any errors printed.
Have a look at the documentation as well. It describes how to use the tool.

**Comment by shubhampateliitm** [comment]
Ok, thanks. I will try.
